name: Auto test

on:
  push:
    branches: master


env:
  IMAGE_ID: "oitnes/conan_with_boost_opencv"
  IMAGE_VERSION: "1.0"
  TEST_IMAGE_TAG: "test"


jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull
        run: docker pull "${IMAGE_ID}:${IMAGE_VERSION}"

      - name: Build
        run: docker build -t ${TEST_IMAGE_TAG} -f Dockerfile --build-arg DOCKER_IMAGE=${IMAGE_ID} --build-arg IMAGE_VERSION=${IMAGE_VERSION} ${PWD}

      - name: Run
        run: docker run ${TEST_IMAGE_TAG}
